services:
  blinddate-dev:
    image: blinddate-dev
    container_name: blinddate-dev
    privileged: true
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /blinddate
    ports:
      - "4199:4199"
    volumes:
      - ..:/blinddate:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
